# Generated by Django 4.0.4 on 2022-05-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_agenda_data_end_alter_agenda_data_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contas',
            new_name='Conta',
        ),
        migrations.RenameModel(
            old_name='Lideres',
            new_name='Lider',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
