# Generated by Django 4.0.4 on 2022-05-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_contas_conta_rename_lideres_lider_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
    ]
