# Generated by Django 4.0.4 on 2022-05-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_eventos_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lider',
            old_name='email_lidere',
            new_name='email_lider',
        ),
        migrations.RenameField(
            model_name='lider',
            old_name='name_lidere',
            new_name='name_lider',
        ),
        migrations.RenameField(
            model_name='lider',
            old_name='numero_lideres',
            new_name='numero_lider',
        ),
    ]
