# Generated by Django 4.0.4 on 2022-05-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_email_id_contato_alter_email_email_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=models.ImageField(blank=True, help_text='Size: 1920x570', upload_to='eventos/'),
        ),
        migrations.DeleteModel(
            name='Systema',
        ),
    ]
