# Generated by Django 4.0.4 on 2022-05-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_evento_image_delete_systema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lider',
        ),
    ]
