# Generated by Django 4.0.4 on 2022-05-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_lider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
