# Generated by Django 4.0.4 on 2022-05-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_conta_data_start_alter_conta_data_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='link',
        ),
    ]
