# Generated by Django 4.0.4 on 2022-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_slide_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
