# Generated by Django 4.0.4 on 2022-06-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contato_telefone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conta',
        ),
    ]
