# Generated by Django 4.0.4 on 2022-06-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='quantidade_ingressos',
        ),
    ]
